### ISSUE TITLE
Allow period ('.') character in name of custom PKGBUILD packages

### ISSUE THREAD

**Issue by jasyip** [Morganamilo/paru#1082]
### Affected Version
**paru -V**
paru v2.0.0 - libalpm v13.0.2
### Description
The new feature of specifying custom PKGBUILDs in `paru.conf` does not allow package names to have a period in them, even if your package name needs a period. There are many AUR packages whose names have periods in them.

### Output
paru.conf:
```toml
[whisper.cpp-clblast]
Path = ~/aur/whisper.cpp-clblast
```

Command:
```sh
~ paru
error: section can not be called whisper.cpp-clblast
```
