### ISSUE TITLE
Timeout looking for devel update, when multiple packages use the same github repo.

### ISSUE THREAD

**Issue by JonathanSteininger** [Morganamilo/paru#1327]
### Affected Version
paru v2.0.4 - libalpm v15.0.0

### Description
**Have you checked previous issues?**
Yes

I had made an [issue](https://github.com/Aylur/astal/issues/265) on the Astal github project about this already. 
But it felt more relevant as an issue with paru itself.

The "looking for devel upgrades" step is timing out due to the [aylurs-gtk-shell](https://aur.archlinux.org/packages/aylurs-gtk-shell) package, and its [libastal-meta](https://aur.archlinux.org/packages/libastal-meta) packages. Because there are multiple sub packages that all use the same parent repository (https://github.com/Aylur/astal.git). 

When paru tries to check the hash of the github repos. All the libastal-meta packages all use the same github repository. So multiple requests get made to get the latest hash. 

My guess is that this is causing github to deny requests due to looking like spam, leading to the timeout.

#### terminal output:

```
paru -Syu
[sudo] password for Aureus:
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 extra-testing is up to date
 multilib is up to date
:: Starting full system upgrade...
 there is nothing to do
:: Looking for PKGBUILD upgrades...
:: Looking for AUR upgrades...
:: Looking for devel upgrades...
error: timed out looking for devel update: https://github.com/libimobiledevice/libplist
error: timed out looking for devel update: https://github.com/hyprwm/hyprcursor.git
error: timed out looking for devel update: https://github.com/Aylur/astal.git
error: timed out looking for devel update: https://github.com/Aylur/astal.git
error: timed out looking for devel update: https://github.com/hyprwm/hyprgraphics.git
error: timed out looking for devel update: https://github.com/hyprwm/hyprwayland-scanner.git
error: timed out looking for devel update: https://github.com/hyprwm/hyprpaper.git
:: Resolving dependencies...
:: Calculating conflicts...
```
#### devel.toml section
```toml
[[libastal-apps-git]]
url = "https://github.com/Aylur/astal.git"
commit = "127e9cdcbf173846a3c40ddc0abfbb038df48042"

[[libastal-auth-git]]
url = "https://github.com/Aylur/astal.git"
commit = "127e9cdcbf173846a3c40ddc0abfbb038df48042"

[[libastal-battery-git]]
url = "https://github.com/Aylur/astal.git"
commit = "127e9cdcbf173846a3c40ddc0abfbb038df48042"

[[libastal-bluetooth-git]]
url = "https://github.com/Aylur/astal.git"
commit = "127e9cdcbf173846a3c40ddc0abfbb038df48042"

[[libastal-cava-git]]
url = "https://github.com/Aylur/astal.git"
commit = "127e9cdcbf173846a3c40ddc0abfbb038df48042"

[[libastal-git]]
url = "https://github.com/Aylur/astal.git"
commit = "127e9cdcbf173846a3c40ddc0abfbb038df48042"

[[libastal-gjs-git]]
url = "https://github.com/Aylur/astal.git"
commit = "127e9cdcbf173846a3c40ddc0abfbb038df48042"

[[libastal-greetd-git]]
url = "https://github.com/Aylur/astal.git"
commit = "127e9cdcbf173846a3c40ddc0abfbb038df48042"

[[libastal-hyprland-git]]
url = "https://github.com/Aylur/astal.git"
commit = "127e9cdcbf173846a3c40ddc0abfbb038df48042"

[[libastal-io-git]]
url = "https://github.com/Aylur/astal.git"
commit = "127e9cdcbf173846a3c40ddc0abfbb038df48042"

[[libastal-mpris-git]]
url = "https://github.com/Aylur/astal.git"
commit = "127e9cdcbf173846a3c40ddc0abfbb038df48042"

[[libastal-network-git]]
url = "https://github.com/Aylur/astal.git"
commit = "127e9cdcbf173846a3c40ddc0abfbb038df48042"

[[libastal-notifd-git]]
url = "https://github.com/Aylur/astal.git"
commit = "127e9cdcbf173846a3c40ddc0abfbb038df48042"

[[libastal-powerprofiles-git]]
url = "https://github.com/Aylur/astal.git"
commit = "127e9cdcbf173846a3c40ddc0abfbb038df48042"

[[libastal-river-git]]
url = "https://github.com/Aylur/astal.git"
commit = "127e9cdcbf173846a3c40ddc0abfbb038df48042"

[[libastal-tray-git]]
url = "https://github.com/Aylur/astal.git"
commit = "127e9cdcbf173846a3c40ddc0abfbb038df48042"

[[libastal-wireplumber-git]]
url = "https://github.com/Aylur/astal.git"
commit = "127e9cdcbf173846a3c40ddc0abfbb038df48042"


```
