### ISSUE TITLE
Specify makepkg config for differnt package

### ISSUE THREAD

**Issue by RustemB** [Morganamilo/paru#188]
Not sure if this good idea, but it can help with building packages that cant be build with custom config
Like env files in Gentoo's poratge
For example, I use `clang` but I can't build some packages with it
In config it might me like that
```toml
[MConf]
pkg-1 = "/path/to/config-1.conf"
pkg-2 = "/path/to/config-2.conf"
...
```
(or not)
