### ISSUE TITLE
Removing cargo deps

### ISSUE THREAD

**Issue by Morganamilo** [Morganamilo/paru#613]
There's a couple of deps that could be removed eventually which should help with compile time + binary size:

```toml
htmlescape = "0.3.1"                                             # aur rpc should get comment support eventually
kuchiki = "0.8.1"                                                # aur rpc should get comment support eventually                          
once_cell = "1.8.0"                                              # should be stable in std eventually
rss = { version = "2.0.0", default-features = false }            # defer to a binary to get the news, are there any good ones?
```

Aditionally reqwest/tokio could be dropped with a little bit of headache

```toml
reqwest = { version = "0.11.6", features = ["gzip", "socks"] }   # could use curl instead but would lose async support
tokio = { version = "1.14.0", features = ["process"] }           # would lose async support
futures = "0.3.18"                                               # not needed if no tokio
```

Curl could be used instead of reqwest. This is good as pacman already deps curl. One issue is we may lose async web requests which we currently make use of to do some requests in parallel (mostly devel checks + update checks). There also appears to be a tokio async provider but that doesn't seem too popular so I wouldn't want to reply on it.

Sync curl would let us also drop tokio and the whole async stack but we would have to use a threadpool for parallel requests. Realisitcly we're probably never doing more than 30 requests. Spawning 30 threads probably is not that bad.
