### ISSUE TITLE
Devel package update fail

### ISSUE THREAD

**Issue by silentnoodlemaster** [Morganamilo/paru#777]
### Affected Version
paru v1.10.0 - libalpm v13.0.1

### Description
[most-git](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=most-git) package failing to install because `pkgver()` is ran in existing `$srcdir`, while the issue should be fixed in the PKGBUILD, think an option to never re-use a srcdir could be useful.

EDIT: on closer inspection, pkgver running without prepare is the cause of the issue

### Output
paru -S most-git              
```
:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...

Aur (1) most-git-5.2.0.pre9-1

:: Proceed to review? [Y/n]: y

:: Downloading PKGBUILDs...
 (1/1) most-git-5.2.0.pre9-1                         [-----------------------------------------]
 nothing new to review
fetching devel info...
==> Making package: most-git 5.2.0.pre9-1 (Wed 22 Jun 2022 09:08:13 AM EEST)
==> Retrieving sources...
  -> Updating most git repo...
Fetching origin
==> Validating source files with md5sums...
    most ... Skipped
==> Making package: most-git 5.2.0.pre9-1 (Wed 22 Jun 2022 09:08:14 AM EEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating most git repo...
Fetching origin
==> Validating source files with md5sums...
    most ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of most git repo...
Cloning into 'most'...
done.
==> Starting prepare()...
==> Starting pkgver()...
==> Updated version: most-git 5.2.0.pre11-1
==> Sources are ready.
most-git-5.2.0.pre9-1: parsing pkg list...
==> Making package: most-git 5.2.0.pre11-1 (Wed 22 Jun 2022 09:08:16 AM EEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Updated version: most-git .pre-1
==> Starting build()...
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking whether gcc needs -traditional... no
checking for library containing strerror... none required
checking C compiler that understands ANSI prototypes... gcc looks ok.  Good.
checking whether make sets $(MAKE)... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking for dlopen in -ldl... yes
checking for X... libraries , headers 
checking for gethostbyname... yes
checking for connect... yes
checking for remove... yes
checking for shmat... yes
checking for IceConnectionNumber in -lICE... yes
checking if you want to use mmap if available... yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for memory.h... (cached) yes
checking malloc.h usability... yes
checking malloc.h presence... yes
checking for malloc.h... yes
checking termios.h usability... yes
checking termios.h presence... yes
checking for termios.h... yes
checking sys/mman.h usability... yes
checking sys/mman.h presence... yes
checking for sys/mman.h... yes
checking for dirent.h that defines DIR... yes
checking for library containing opendir... none required
checking for mode_t... yes
checking for pid_t... yes
checking for uid_t in sys/types.h... yes
checking for size_t... yes
checking size of short... 2
checking size of int... 4
checking size of long... 8
checking size of float... 4
checking size of double... 8
checking for long long... yes
checking size of long long... 8
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for _LARGEFILE_SOURCE value needed for large files... no
checking for off_t... yes
checking size of off_t... 8
checking for memset... yes
checking for memcpy... yes
checking for putenv... yes
checking for getcwd... yes
checking for mmap... yes
checking for snprintf... yes
checking for getpgrp... yes
checking for tcgetpgrp... yes
checking for ncurses5-config... no
checking for ncursesw5-config... (cached) no
checking for terminfo... yes
checking for the slang library and header files ... yes: /usr/lib and /usr/include
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating src/sysconf.h
cd src; make all
make[1]: Entering directory '/home/noodle/.cache/paru/clone/most-git/src/most/src'
mkdir /home/noodle/.cache/paru/clone/most-git/src/most/src/objs
/bin/cp /home/noodle/.cache/paru/clone/most-git/src/most/src/sysconf.h config.h
cd /home/noodle/.cache/paru/clone/most-git/src/most/src/objs && gcc -c -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection  -Dunix  -DMOST_SYSTEM_INITFILE='"/etc/most.conf"'  /home/noodle/.cache/paru/clone/most-git/src/most/src/chkslang.c
gcc /home/noodle/.cache/paru/clone/most-git/src/most/src/objs/chkslang.o -o /home/noodle/.cache/paru/clone/most-git/src/most/src/objs/chkslang -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now  -lslang  -lm
/home/noodle/.cache/paru/clone/most-git/src/most/src/objs/chkslang most 20000
cd /home/noodle/.cache/paru/clone/most-git/src/most/src/objs && gcc -c -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection  -Dunix  -DMOST_SYSTEM_INITFILE='"/etc/most.conf"'  /home/noodle/.cache/paru/clone/most-git/src/most/src/buffer.c
cd /home/noodle/.cache/paru/clone/most-git/src/most/src/objs && gcc -c -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection  -Dunix  -DMOST_SYSTEM_INITFILE='"/etc/most.conf"'  /home/noodle/.cache/paru/clone/most-git/src/most/src/cmd.c
cd /home/noodle/.cache/paru/clone/most-git/src/most/src/objs && gcc -c -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection  -Dunix  -DMOST_SYSTEM_INITFILE='"/etc/most.conf"'  /home/noodle/.cache/paru/clone/most-git/src/most/src/display.c
cd /home/noodle/.cache/paru/clone/most-git/src/most/src/objs && gcc -c -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection  -Dunix  -DMOST_SYSTEM_INITFILE='"/etc/most.conf"'  /home/noodle/.cache/paru/clone/most-git/src/most/src/edit.c
cd /home/noodle/.cache/paru/clone/most-git/src/most/src/objs && gcc -c -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection  -Dunix  -DMOST_SYSTEM_INITFILE='"/etc/most.conf"'  /home/noodle/.cache/paru/clone/most-git/src/most/src/file.c
/home/noodle/.cache/paru/clone/most-git/src/most/src/file.c: In function ‘expand_path’:
/home/noodle/.cache/paru/clone/most-git/src/most/src/file.c:746:16: warning: ignoring return value of ‘chdir’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  746 |         (void) chdir(Most_C_Dir);
      |                ^~~~~~~~~~~~~~~~~
/home/noodle/.cache/paru/clone/most-git/src/most/src/file.c: In function ‘most_get_cdir’:
/home/noodle/.cache/paru/clone/most-git/src/most/src/file.c:838:4: warning: ignoring return value of ‘getcwd’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  838 |    getcwd(dir, MAX_PATHLEN);
      |    ^~~~~~~~~~~~~~~~~~~~~~~~
cd /home/noodle/.cache/paru/clone/most-git/src/most/src/objs && gcc -c -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection  -Dunix  -DMOST_SYSTEM_INITFILE='"/etc/most.conf"'  /home/noodle/.cache/paru/clone/most-git/src/most/src/help.c
cd /home/noodle/.cache/paru/clone/most-git/src/most/src/objs && gcc -c -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection  -Dunix  -DMOST_SYSTEM_INITFILE='"/etc/most.conf"'  /home/noodle/.cache/paru/clone/most-git/src/most/src/keym.c
cd /home/noodle/.cache/paru/clone/most-git/src/most/src/objs && gcc -c -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection  -Dunix  -DMOST_SYSTEM_INITFILE='"/etc/most.conf"'  /home/noodle/.cache/paru/clone/most-git/src/most/src/keyparse.c
cd /home/noodle/.cache/paru/clone/most-git/src/most/src/objs && gcc -c -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection  -Dunix  -DMOST_SYSTEM_INITFILE='"/etc/most.conf"'  /home/noodle/.cache/paru/clone/most-git/src/most/src/line.c
cd /home/noodle/.cache/paru/clone/most-git/src/most/src/objs && gcc -c -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection  -Dunix  -DMOST_SYSTEM_INITFILE='"/etc/most.conf"'  /home/noodle/.cache/paru/clone/most-git/src/most/src/main.c
cd /home/noodle/.cache/paru/clone/most-git/src/most/src/objs && gcc -c -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection  -Dunix  -DMOST_SYSTEM_INITFILE='"/etc/most.conf"'  /home/noodle/.cache/paru/clone/most-git/src/most/src/most.c
cd /home/noodle/.cache/paru/clone/most-git/src/most/src/objs && gcc -c -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection  -Dunix  -DMOST_SYSTEM_INITFILE='"/etc/most.conf"'  /home/noodle/.cache/paru/clone/most-git/src/most/src/search.c
cd /home/noodle/.cache/paru/clone/most-git/src/most/src/objs && gcc -c -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection  -Dunix  -DMOST_SYSTEM_INITFILE='"/etc/most.conf"'  /home/noodle/.cache/paru/clone/most-git/src/most/src/sysdep.c
cd /home/noodle/.cache/paru/clone/most-git/src/most/src/objs && gcc -c -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection  -Dunix  -DMOST_SYSTEM_INITFILE='"/etc/most.conf"'  /home/noodle/.cache/paru/clone/most-git/src/most/src/window.c
cd /home/noodle/.cache/paru/clone/most-git/src/most/src/objs && gcc -c -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection  -Dunix  -DMOST_SYSTEM_INITFILE='"/etc/most.conf"'  /home/noodle/.cache/paru/clone/most-git/src/most/src/color.c
cd /home/noodle/.cache/paru/clone/most-git/src/most/src/objs; gcc buffer.o cmd.o display.o edit.o file.o help.o keym.o keyparse.o line.o main.o most.o search.o sysdep.o window.o color.o -o most -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now  -lslang  -lm
most created in /home/noodle/.cache/paru/clone/most-git/src/most/src/objs
make[1]: Leaving directory '/home/noodle/.cache/paru/clone/most-git/src/most/src'
==> Entering fakeroot environment...
==> Starting package()...
cd src; make all
make[1]: Entering directory '/home/noodle/.cache/paru/clone/most-git/src/most/src'
/home/noodle/.cache/paru/clone/most-git/src/most/src/objs/chkslang most 20000
most created in /home/noodle/.cache/paru/clone/most-git/src/most/src/objs
make[1]: Leaving directory '/home/noodle/.cache/paru/clone/most-git/src/most/src'
cd src; make install
make[1]: Entering directory '/home/noodle/.cache/paru/clone/most-git/src/most/src'
/home/noodle/.cache/paru/clone/most-git/src/most/src/objs/chkslang most 20000
most created in /home/noodle/.cache/paru/clone/most-git/src/most/src/objs
../autoconf/mkinsdir.sh /home/noodle/.cache/paru/clone/most-git/pkg/most-git/usr/share/doc/most
mkdir /home/noodle/.cache/paru/clone/most-git/pkg/most-git/usr
mkdir /home/noodle/.cache/paru/clone/most-git/pkg/most-git/usr/share
mkdir /home/noodle/.cache/paru/clone/most-git/pkg/most-git/usr/share/doc
mkdir /home/noodle/.cache/paru/clone/most-git/pkg/most-git/usr/share/doc/most
../autoconf/mkinsdir.sh /home/noodle/.cache/paru/clone/most-git/pkg/most-git/usr/share/man/man1
mkdir /home/noodle/.cache/paru/clone/most-git/pkg/most-git/usr/share/man
mkdir /home/noodle/.cache/paru/clone/most-git/pkg/most-git/usr/share/man/man1
../autoconf/mkinsdir.sh /home/noodle/.cache/paru/clone/most-git/pkg/most-git/usr/bin
mkdir /home/noodle/.cache/paru/clone/most-git/pkg/most-git/usr/bin
/usr/bin/install -c -s /home/noodle/.cache/paru/clone/most-git/src/most/src/objs/most /home/noodle/.cache/paru/clone/most-git/pkg/most-git/usr/bin
/usr/bin/install -c -m 644 ../doc/most.1 /home/noodle/.cache/paru/clone/most-git/pkg/most-git/usr/share/man/man1
/usr/bin/install -c -m 644 ../doc/most.txt /home/noodle/.cache/paru/clone/most-git/pkg/most-git/usr/share/doc/most/
/usr/bin/install -c -m 644 ../README /home/noodle/.cache/paru/clone/most-git/pkg/most-git/usr/share/doc/most/
/usr/bin/install -c -m 644 ../doc/most-fun.txt /home/noodle/.cache/paru/clone/most-git/pkg/most-git/usr/share/doc/most/
/usr/bin/install -c -m 644 ../doc/lesskeys.rc /home/noodle/.cache/paru/clone/most-git/pkg/most-git/usr/share/doc/most/
/usr/bin/install -c -m 644 ../doc/most.rc /home/noodle/.cache/paru/clone/most-git/pkg/most-git/usr/share/doc/most/
/usr/bin/install -c -m 644 ../changes.txt /home/noodle/.cache/paru/clone/most-git/pkg/most-git/usr/share/doc/most/
make[1]: Leaving directory '/home/noodle/.cache/paru/clone/most-git/src/most/src'
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> Creating package "most-git"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: most-git .pre-1 (Wed 22 Jun 2022 09:08:21 AM EEST)
==> Cleaning up...
loading packages...
error: '/home/noodle/.cache/paru/clone/most-git/most-git-5.2.0.pre11-1-x86_64.pkg.tar.zst': could not find or read package
```
pacman.conf
```toml
#
# /etc/pacman.conf
#
# See the pacman.conf(5) manpage for option and repository directives

#
# GENERAL OPTIONS
#
[options]
# The following paths are commented out with their default values listed.
# If you wish to use different paths, uncomment and update the paths.
#RootDir     = /
#DBPath      = /var/lib/pacman/
#CacheDir    = /var/cache/pacman/pkg/
#LogFile     = /var/log/pacman.log
#GPGDir      = /etc/pacman.d/gnupg/
#HookDir     = /etc/pacman.d/hooks/
HoldPkg     = pacman glibc
#XferCommand = /usr/bin/curl -L -C - -f -o %o %u
#XferCommand = /usr/bin/wget --passive-ftp -c -O %o %u
#CleanMethod = KeepInstalled
Architecture = auto

# Pacman won't upgrade packages listed in IgnorePkg and members of IgnoreGroup
#IgnorePkg   =
#IgnoreGroup =

#NoUpgrade   =
#NoExtract   =

# Misc options
#UseSyslog
Color
#NoProgressBar
CheckSpace
#VerbosePkgLists
ParallelDownloads = 5
ILoveCandy

# By default, pacman accepts packages signed by keys that its local keyring
# trusts (see pacman-key and its man page), as well as unsigned packages.
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional
#RemoteFileSigLevel = Required

# NOTE: You must run `pacman-key --init` before first using pacman; the local
# keyring can then be populated with the keys of all official Arch Linux
# packagers with `pacman-key --populate archlinux`.

#
# REPOSITORIES
#   - can be defined here or included from another file
#   - pacman will search repositories in the order defined here
#   - local/custom mirrors can be added here or in separate files
#   - repositories listed first will take precedence when packages
#     have identical names, regardless of version number
#   - URLs will have $repo replaced by the name of the current repo
#   - URLs will have $arch replaced by the name of the architecture
#
# Repository entries are of the format:
#       [repo-name]
#       Server = ServerName
#       Include = IncludePath
#
# The header [repo-name] is crucial - it must be present and
# uncommented to enable the repo.
#

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[community]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist


## Testing at botton to never automatically use

[testing]
Include = /etc/pacman.d/mirrorlist
[community-testing]
Include = /etc/pacman.d/mirrorlist
[multilib-testing]
Include = /etc/pacman.d/mirrorlist

## Third party
[kernel]
Server = https://repo.blacksky3.com/$arch/$repo
SigLevel = Never

[home-thaodan]
Server = https://thaodan.de/public/archlinux/home-thaodan/$arch

#[rumpowered]
#SigLevel = Never
#Server = https://raw.githubusercontent.com/jc141x/rumpowered-packages/master/$arch
#Server = file:///home/noodle/repo/$arch
```
paru.conf
```toml
# See the paru.conf(5) manpage for options
[options]
PgpFetch
Devel
Provides
DevelSuffixes = -git -cvs -svn -bzr -darcs -always -hg
#AurOnly
#BottomUp
#RemoveMake = ask
SudoLoop
#UseAsk
SaveChanges
CombinedUpgrade
CleanAfter
#UpgradeMenu
NewsOnUpgrade
BatchInstall
#LocalRepo
#Chroot
#Sign
#SignDb
#KeepRepoCache
Redownload = all
Rebuild = all

[bin]
#FileManager = nnn
#MFlags = --skippgpcheck
#Sudo = doas
```
